<h3>ones()</h3>

>#creates array filled with ones.

In [1]:
from numpy import*

In [2]:
arr=ones(5)
print(arr)

[1. 1. 1. 1. 1.]


>#[1. 1. 1. 1. 1.] this values is in the float form because default value is always is in the float from 
>if you want to change the value you have to mention dtype for it like in below.

In [3]:
arr1=ones(5,int)
print(arr1)

[1 1 1 1 1]


In [4]:
arr2=ones((2,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
arr3=ones((5,),int)
arr3

array([1, 1, 1, 1, 1])

In [6]:
arr=ones((5),int)
print(arr)

[1 1 1 1 1]


In [7]:
s = (2,3)
arr4=ones(s)
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
help(ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

><a href="https://www.youtube.com/watch?v=i4EBrUYZHNc&list=PLzgPDYo_3xunaO-noMnBzc3KzzToOcxVY&index=10">Ones</a>

><a href="https://github.com/Kushal997-das/basic-libraries-in-python/blob/master/numpy/5.zeros().ipynb">Prev<br>zeros()</a>

><a href="https://github.com/Kushal997-das/basic-libraries-in-python/blob/master/numpy/7.eye().ipynb">Next<br>eye()</a>