<h3>identity()</h3>

>#it creates square matrix

In [1]:
from numpy import*

In [2]:
arr=identity(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
arr1=identity(5,int)
print(arr1)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [4]:
help(identity)

Help on function identity in module numpy:

identity(n, dtype=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    
    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.
    
    Examples
    --------
    >>> np.identity(3)
    array([[1.,  0.,  0.],
           [0.,  1.,  0.],
           [0.,  0.,  1.]])



><a href='https://www.youtube.com/watch?v=EzOjhjFfM-w'>identity()</a>

><a href="https://github.com/Kushal997-das/basic-libraries-in-python/blob/master/numpy/7.eye().ipynb">Prev<br>eye()</a>

><a href="https://github.com/Kushal997-das/basic-libraries-in-python/blob/master/numpy/9.random.ipynb">Next<br>random()</a>