<h3>arange() method:(arrayrange)</h3>

>so difference between range() and arange() is that range() function is used for class while arange() function is used for 
only 3rd party which numpy in this case.in a word you can range() is used for class and arange() is used for numpy.

In [1]:
from numpy import*

In [2]:
arr=arange(0,12,5)
print(arr)

[ 0  5 10]


In [3]:
arr=arange(0,12,5)
print(arr)

[ 0  5 10]


In [4]:
arr1=arange(0,23,2,dtype='complex')
print(arr1)

[ 0.+0.j  2.+0.j  4.+0.j  6.+0.j  8.+0.j 10.+0.j 12.+0.j 14.+0.j 16.+0.j
 18.+0.j 20.+0.j 22.+0.j]


In [5]:
arr1=arange(0,23,dtype='int') 
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


>#if you don't write dtype here is also working fine.

In [6]:
arr=arange(0,13)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
help(arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

><a href="https://www.youtube.com/watch?v=vRRifcvGCkA&list=PLzgPDYo_3xunaO-noMnBzc3KzzToOcxVY&index=7">arange()</a><br>