<h3>eye()</h3>

>#returns array filled with zero except diagonal whose values are equal to 1

In [1]:
import numpy as np

In [2]:
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


>#Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [3]:
arr1=np.eye(5,k=1,dtype='int')
print(arr1)

[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


>here i wrote k=1 that means above one step of daigonal

In [4]:
arr1=np.eye(5,k=-1,dtype='int')
print(arr1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


>here i wrote k=-1 that means below one step of daigonal

In [5]:
arr2=np.eye(5,2,k=1,dtype='int')
print(arr2)

[[0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [18]:
arr3=np.eye(5,2,k=1,dtype='int')
print(arr3)

[[0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [15]:
arr3=np.eye(5,2,k=1,dtype='int',order='F')#F=column major
print(arr3)

[[0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [17]:
arr4=np.eye(5,order='C')#C=row major
print(arr4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
arr5=np.eye(5,order='F')
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

><a href="https://www.youtube.com/watch?v=EzOjhjFfM-w">eye()</a>