<h3>Zeros() </h3>

>#creates array filled with zero.

In [1]:
from numpy import*

In [2]:
arr=zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


>#[0. 0. 0. 0. 0.] this values is in the float form because default value is always is in the float from 
>if you want to change the value you have to mention dtype for it like in below.

In [3]:
arr1=zeros(5,int)
print(arr1)

[0 0 0 0 0]


In [4]:
arr2=zeros((2,3))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
s = [2,3]
arr4=zeros(s)
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
help(zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

><a href="https://www.youtube.com/watch?v=qx70kifeRC8&list=PLzgPDYo_3xunaO-noMnBzc3KzzToOcxVY&index=8">zeros</a>